--liquibase formatted sql

--changeset mimp:001-schema
CREATE SCHEMA IF NOT EXISTS mimp;

CREATE TABLE IF NOT EXISTS mimp.stg_proteccion_especial (
    report_year text,
    report_period text,
    report_date text,
    entity_code text,
    program_name text,
    line_code text,
    line_name text,
    service_code text,
    service_name text,
    ubigeo text,
    department text,
    province text,
    district text,
    center_code text,
    center_name text,
    num_ca text,
    total_nna text,
    male_nna text,
    female_nna text,
    age_0_5_total text,
    age_0_5_male text,
    age_0_5_female text,
    age_6_11_total text,
    age_6_11_male text,
    age_6_11_female text,
    age_12_17_total text,
    age_12_17_male text,
    age_12_17_female text,
    age_18_plus_total text,
    age_18_plus_male text,
    age_18_plus_female text,
    source_snapshot text
);

CREATE TABLE IF NOT EXISTS mimp.dim_geography (
    ubigeo varchar(6) PRIMARY KEY,
    department text,
    province text,
    district text
);

CREATE TABLE IF NOT EXISTS mimp.dim_service (
    service_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_code text,
    program_name text,
    line_code text,
    line_name text,
    service_code text,
    service_name text,
    CONSTRAINT uq_dim_service_codes UNIQUE (entity_code, line_code, service_code)
);

CREATE TABLE IF NOT EXISTS mimp.dim_center (
    center_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_code text NOT NULL,
    center_name text,
    num_ca integer,
    ubigeo varchar(6) REFERENCES mimp.dim_geography (ubigeo),
    service_key bigint NOT NULL REFERENCES mimp.dim_service (service_key),
    CONSTRAINT uq_dim_center_service UNIQUE (center_code, service_key)
);

CREATE TABLE IF NOT EXISTS mimp.fact_admissions (
    admission_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year integer NOT NULL,
    report_period text,
    report_date date NOT NULL,
    center_key bigint NOT NULL REFERENCES mimp.dim_center (center_key),
    total_nna integer CHECK (total_nna IS NULL OR total_nna >= 0),
    male_nna integer CHECK (male_nna IS NULL OR male_nna >= 0),
    female_nna integer CHECK (female_nna IS NULL OR female_nna >= 0),
    age_0_5_total integer CHECK (age_0_5_total IS NULL OR age_0_5_total >= 0),
    age_0_5_male integer CHECK (age_0_5_male IS NULL OR age_0_5_male >= 0),
    age_0_5_female integer CHECK (age_0_5_female IS NULL OR age_0_5_female >= 0),
    age_6_11_total integer CHECK (age_6_11_total IS NULL OR age_6_11_total >= 0),
    age_6_11_male integer CHECK (age_6_11_male IS NULL OR age_6_11_male >= 0),
    age_6_11_female integer CHECK (age_6_11_female IS NULL OR age_6_11_female >= 0),
    age_12_17_total integer CHECK (age_12_17_total IS NULL OR age_12_17_total >= 0),
    age_12_17_male integer CHECK (age_12_17_male IS NULL OR age_12_17_male >= 0),
    age_12_17_female integer CHECK (age_12_17_female IS NULL OR age_12_17_female >= 0),
    age_18_plus_total integer CHECK (age_18_plus_total IS NULL OR age_18_plus_total >= 0),
    age_18_plus_male integer CHECK (age_18_plus_male IS NULL OR age_18_plus_male >= 0),
    age_18_plus_female integer CHECK (age_18_plus_female IS NULL OR age_18_plus_female >= 0),
    source_snapshot text,
    loaded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_fact_admission UNIQUE (report_year, report_date, center_key)
);

CREATE INDEX IF NOT EXISTS ix_fact_admissions_year
    ON mimp.fact_admissions (report_year);
CREATE INDEX IF NOT EXISTS ix_fact_admissions_center
    ON mimp.fact_admissions (center_key);
